[project]
name = "rock-the-jvm-spark-cluster"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "boto3>=1.38.23",
    "requests>=2.32.3",
]
